# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
version: 0.2

phases:
  install:
    commands:
      - echo Installing boto3 python sdk
      - pip install boto3
  build:
    commands:
      - echo Build started on `date`
      - echo Running Python deploy script 
      - python deploy.py $CODEBUILD_SRC_DIR_TrainerArtifacts/job.txt
