# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
version: 0.2

phases:
  install:
    commands:
      - echo Installing SageMaker python sdk
      - pip install sagemaker
  build:
    commands:
      - echo Build started on `date`
      - echo Running Python training script 
      - python trainer.py job.txt $NOOP
artifacts:
  files: 
    - 'job.txt'
